sudo: required
services:
  - docker

before_install:
  - docker build -t apaspul/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run apaspul/react-test npm test -- --coverage

after_success:
  - docker build -t apasupul/multi-client ./client 
  - docker build -t apasupul/multi-nginx ./nginx
  - docker build -t apasupul/multi-server ./server
  - docker build -t apasupul/multi-worker ./worker
  # log in to to the docker cli 
  - echo  "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  #take those images and push themt o docekr hub 
  - docker push apasupul/multi-client
  - docker push apasupul/multi-nginx
  - docker push apasupul/multi-server
  - docker push apasupul/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-724190275674
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWSSECRET_KEY
